export let Userdata = [
  {
    "id": 23,
    "displayName": "J Quibseed",
    "firstName": "Sarah",
    "lastName": "Doyle",
    "email": "punkrockprincess@gmail.com",
    "joinDate": "2015/12/23",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 24,
    "displayName": "M. Maisonpierre",
    "firstName": "michael",
    "lastName": "maison",
    "email": "punkrockprincess@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Pending"
  },
  {
    "id": 25,
    "displayName": "A Matecki",
    "firstName": "Andrew",
    "lastName": "Matecki",
    "email": "Andrewmatecki@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 26,
    "displayName": "Will Holsclaw",
    "firstName": "Will",
    "lastName": "Holsclaw",
    "email": "wholsclaw@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 30,
    "displayName": "Will Holsclaw",
    "firstName": "Will",
    "lastName": "Holsclaw",
    "email": "wholsclaw@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 50,
    "displayName": "A Matecki",
    "firstName": "Andrew",
    "lastName": "Matecki",
    "email": "Andrewmatecki@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 90,
    "displayName": "Will Holsclaw",
    "firstName": "Will",
    "lastName": "Holsclaw",
    "email": "wholsclaw@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 150,
    "displayName": "A Matecki",
    "firstName": "Andrew",
    "lastName": "Matecki",
    "email": "Andrewmatecki@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 120,
    "displayName": "Will Holsclaw",
    "firstName": "Will",
    "lastName": "Holsclaw",
    "email": "wholsclaw@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 300,
    "displayName": "A Matecki",
    "firstName": "Andrew",
    "lastName": "Matecki",
    "email": "Andrewmatecki@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 130,
    "displayName": "A Matecki",
    "firstName": "Andrew",
    "lastName": "Matecki",
    "email": "Andrewmatecki@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  },
  {
    "id": 200,
    "displayName": "Will Holsclaw",
    "firstName": "Will",
    "lastName": "Holsclaw",
    "email": "wholsclaw@gmail.com",
    "joinDate": "12/20/22022",
    "bmp": "02",
    "fng": "25",
    "frs": "65",
    "unp": "98",
    "status": "Approved"
  }
]

export let MovieData = [
  { "id":1,
    "title": "Arrival",
    "director": "Denis Villeneuve",
    "releaseyear": 2016,
    "length": 6981,
    "status": "Active",
  },
  { "id":2,
    "title": "Beasts of No Nation",
    "director": "Cary Joji Fukunaga",
    "releaseyear": 2015,
    "length": 8243,
    "status": "InActive",
  },
  { "id":10,
    "title": "Beasts of No Nation",
    "director": "Cary Joji Fukunaga",
    "releaseyear": 2015,
    "length": 8243,
    "status": "Active",
  },
  { "id":35,
    "title": "Beasts of No Nation",
    "director": "Cary Joji Fukunaga",
    "releaseyear": 2015,
    "length": 8243,
    "status": "Active",
  },
  { "id":3,
    "title": "Birdman",
    "director": "Alejandro González Iñárritu",
    "releaseyear": 2014,
    "length": 7157,
    "status": "InActive",
  },
  { "id":4,
    "title": "Black Panther",
    "director": "Ryan Coogler",
    "releaseyear": 2018,
    "length": 8072,
    "status": "InActive",
  }
]

export let QuibData = [
  {
    "id":12,
    "user": "J Quibseed",
    "movies": "Pulp Fiction",
    "quib": "Definition of pulp",
    "time": "0:00:15",
    "createdDate": "06/23/2013",
    "postedDate": "07/01/2013",
    "isEnabled": "Approved",
    "isBumped": "Saved",
    "quibType": "SQ"
  },
  {
    "id":13,
    "user": "J Quibseed",
    "movies": "Pulp Fiction",
    "quib": "Alright. Same as last time, remember? You're crowd control. I handle employeesp",
    "time": "0:00:15",
    "createdDate": "06/23/2013",
    "postedDate": "07/01/2013",
    "isEnabled": "Approved",
    "isBumped": "unSaved",
    "quibType": "SQ"
  },
  {
    "id":14,
    "user": "J Quibseed",
    "movies": "Pulp Fiction",
    "quib": "Alright. Same as last time, remember? You're crowd control. I handle employees",
    "time": "0:00:15",
    "createdDate": "06/23/2013",
    "postedDate": "07/01/2013",
    "isEnabled": "Decline",
    "isBumped": "unSaved",
    "quibType": "SQ"
  },
  {
    "id":16,
    "user": "J Quibseed",
    "movies": "Pulp Fiction",
    "quib": "Alright. Same as last time, remember? You're crowd control. I handle employees",
    "time": "0:00:15",
    "createdDate": "06/23/2013",
    "postedDate": "07/01/2013",
    "isEnabled": "Approved",
    "isBumped": "Saved",
    "quibType": "SQ"
  },
  {
    "id":17,
    "user": "J Quibseed",
    "movies": "Pulp Fiction",
    "quib": "Alright. Same as last time, remember? You're crowd control. I handle employees",
    "time": "0:00:15",
    "createdDate": "06/23/2013",
    "postedDate": "07/01/2013",
    "isEnabled": "Decline",
    "isBumped": "unSaved",
    "quibType": "SQ"
  }

]